site_name: Git Docs
theme: mkdocs
pages:
- Git:
    - Home: 'index.md'
    - Introdução: 'introducao.md'
    - Lista de comandos: 'comandos.md'
- Básico:
    - Inicializando um projeto: 'inicializando-projeto.md'
    - Criando Histórico: 'criando_historico.md'
    - Boas Práticas de commits: 'boas_praticas.md'
    - Branches: 'branches.md'
    - Merges: 'merges.md'
    - Remotos: 'remotos.md'
    - Fluxos de trabalho: 'fluxos_de_trabalho.md'
    - Github e Gitlab: 'github_gitlab.md'
- Avançado:
    - Recuperando e desfazendo: 'recuperando_desfazendo.md'
    - Patches: 'patches.md'
    - Customizando:  'customizando.md'
    - Ferramentas Auxiliares: 'ferramentas-auxiliares-e-produtividade.md'
    - Criando um servidor git: 'criando_servidor.md'
    - Submódulos: 'submodulos.md'
    - Operadores Relativos: 'operadores_relativos.md'
    - Resolvendo Conflitos: 'resolvendo_conflitos.md'
    - Reescrevendo Histórico: 'reescrevendo-historico.md'
    - Debug: 'debug.md'
    - Manutenção: 'manutencao.md'
    - Recuperando dados:  'recuperando_dados.md'
    - Pumbling: 'pumbling.md'
    - Comandos Menos comuns: 'comandosmenos_comuns.md'
    - Integracoes:  'integracoes.md'
- Conceitos: 'conceitos.md'
- Recursos Adicionais: 'recursos_adicionais.md'
